### ISSUE TITLE
the script can't make new dir

### ISSUE THREAD

**Issue by TWO-ONE-21** [phspade/Automated-Scanner#3]
I was run the script.
bash scanner.sh ayam.com

and the script can't make new dir.

it is the error:

(15:26:51)-(aurora)-(1802)-> bash scanner.sh ayam.com
cat: /home/aurora/tools/.creds: No such file or directory
mkdir: cannot create directory ‘/home/aurora/recon’: File exists
cat: /home/aurora/tools/.creds: No such file or directory
cat: /home/aurora/tools/.creds: No such file or directory
Sun 24 Nov 2019 03:33:15 PM +07
[+] AMASS SCANNING [+]
cat: /home/aurora/tools/.creds: No such file or directory
cat: /home/aurora/tools/.creds: No such file or directory
[!] Skipping ...
[+] FINDOMAIN SCANNING [+]
cat: /home/aurora/tools/.creds: No such file or directory
cat: /home/aurora/tools/.creds: No such file or directory
[!] Skipping ...
[+] SUBFINDER SCANNING [+]
cat: /home/aurora/tools/.creds: No such file or directory
cat: /home/aurora/tools/.creds: No such file or directory
[!] Skipping ...
[+] AQUATONE SCANNING [+]
cat: /home/aurora/aquatone/ayam.com/urls.txt: No such file or directory
cat: /home/aurora/recon/ayam.com/ayam.com-aquatone.txt: No such file or directory
cat: /home/aurora/tools/.creds: No such file or directory
cat: /home/aurora/tools/.creds: No such file or directory
[!] Skipping ...

**Comment by 0xspade** [comment]
You should have the tools folder with .creds file inside of it. check the repository for example.

**Comment by 0xspade** [comment]
and also mind the errors.
