### ISSUE TITLE
Line 256: Too many args.

### ISSUE THREAD

**Issue by 0xcatallena0x** [phspade/Automated-Scanner#4]
Hi spade, first of all I would like you to thank you for such a great tool but I am here to report a problem.
![image](https://user-images.githubusercontent.com/50789123/69861628-97654680-124d-11ea-830d-1a66de92d4d4.png)

**Comment by 0xcatallena0x** [comment]
Please excuse my tone as it may sound like I'm rude actually I just suck in English and I am trying to avoid confusions. Thank you for everything :)

**Comment by 0xspade** [comment]
fixed!
